# Generated by Django 3.0.6 on 2020-05-14 18:35

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField(null=True)),
                ('room', models.URLField(null=True)),
                ('stream', models.URLField(null=True)),
                ('agenda', models.TextField(max_length=2000)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('beers', models.ManyToManyField(to='website.Beer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ManyToManyField(null=True, to='website.Brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ManyToManyField(null=True, to='website.Style'),
        ),
    ]
