# Generated by Django 3.0.6 on 2020-05-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200517_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='brewery',
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Brewery'),
        ),
    ]
