# Generated by Django 3.0.6 on 2020-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200517_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='stream',
            field=models.URLField(blank=True, null=True),
        ),
    ]
